{% set name = "fps-yjs" %}
{% set version = "0.0.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_yjs-{{ version }}.tar.gz
  sha256: 2752fce8562942bbffe344ff78f52697b26305315c3cac744b40883e01cab26a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - fps >=0.0.8,<1
    - fps-auth-base <1
    - fps-contents >=0.0.37,<1
    - jupyter_ydoc >=0.1.16,<0.2.0
    - ypy-websocket >=0.8.2,<1

test:
  imports:
    - fps_yjs

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yjs
  summary: An FPS plugin for the Yjs API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yjs
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
