{% set name = "fps-yjs" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_yjs-{{ version }}.tar.gz
  sha256: bdfdca5e8516d3d5a3db63cd157c549fc90dac6156b22e9913be91df0368a194

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - importlib-metadata >=3.6
    - jupyverse-api >=0.12.0,<0.13.0
    - pycrdt >=0.9.0,<0.13.0
    - sqlite-anyio >=0.2.0,<0.3.0
    - jupyter_ydoc >3.0.1,<4.0.0
    - anyioutils >=0.7.4

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_yjs

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yjs
  summary: An FPS plugin for the Yjs API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yjs
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
