{% set name = "fps-yjs" %}
{% set version = "0.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_yjs-{{ version }}.tar.gz
  sha256: d1619594e86e9484eddbd5db9b655125ffbcb60262e8a54d7495008449589682

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps >=0.0.8,<1.0.0
    - fps-auth >=0.0.30,<1.0.0

test:
  imports:
    - fps_yjs

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yjs
  summary: An FPS plugin for the Yjs API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yjs
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
