schema_version: 1

context:
  version: "0.14.3"

package:
  name: fps-yjs
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-yjs/fps_yjs-${{ version }}.tar.gz
    sha256: 3b6b54e172de7e4bfec4550f2b985a511e7f1ef28710437e503e9df2ef0a33bb

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.11.32,<0.12
  run:
    - python >=${{ python_min }}
    - fastapi-core
    - fps
    - jupyverse-api >=0.15.0,<0.16.0
    - jupyverse-auth >=0.2.0,<0.3.0
    - jupyverse-file-id >=0.1.0,<0.2.0
    - jupyverse-yjs >=0.1.1,<0.2.0
    - jupyverse-yrooms >=0.1.1,<0.2.0
    - pycrdt

tests:
  - python:
      imports: fps_yjs
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yjs
  summary: An FPS plugin for the Yjs API

extra:
  recipe-maintainers:
    - davidbrochart
