schema_version: 1

context:
  version: "0.13.0"

package:
  name: fps-yjs
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-yjs/fps_yjs-${{ version }}.tar.gz
    sha256: 47064725ec8488eb313bcfce12e2b44fd6f5d8a76b6d45a0bf82cd384b637955

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.14.0,<0.15.0

tests:
  - python:
      imports: fps_yjs
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/yjs
  summary: An FPS plugin for the Yjs API

extra:
  recipe-maintainers:
    - davidbrochart
